DELETE FROM toshivepet.core_comuna;
DELETE FROM toshivepet.core_region;

INSERT INTO toshivepet.core_region (codigoRegion, nombreRegion) VALUES (0,'Arica y Parinacota');
INSERT INTO toshivepet.core_region (codigoRegion, nombreRegion) VALUES (1,q'[Tarapacá]');
INSERT INTO toshivepet.core_region (codigoRegion, nombreRegion) VALUES (2,'Antofagasta');
INSERT INTO toshivepet.core_region (codigoRegion, nombreRegion) VALUES (3,'Atacama');
INSERT INTO toshivepet.core_region (codigoRegion, nombreRegion) VALUES (4,'Coquimbo');
INSERT INTO toshivepet.core_region (codigoRegion, nombreRegion) VALUES (5,'Valparaíso');
INSERT INTO toshivepet.core_region (codigoRegion, nombreRegion) VALUES (6,q'[Lib. Gral. Bernardo O Higgins]');
INSERT INTO toshivepet.core_region (codigoRegion, nombreRegion) VALUES (7,'Maule');
INSERT INTO toshivepet.core_region (codigoRegion, nombreRegion) VALUES (8,'Ñuble');
INSERT INTO toshivepet.core_region (codigoRegion, nombreRegion) VALUES (9,'Biobío');
INSERT INTO toshivepet.core_region (codigoRegion, nombreRegion) VALUES (10,'La Araucanía');
INSERT INTO toshivepet.core_region (codigoRegion, nombreRegion) VALUES (11,'Los Ríos');
INSERT INTO toshivepet.core_region (codigoRegion, nombreRegion) VALUES (12,'Los Lagos');
INSERT INTO toshivepet.core_region (codigoRegion, nombreRegion) VALUES (13,'Aysén del General Carlos Ibáñez del Campo');
INSERT INTO toshivepet.core_region (codigoRegion, nombreRegion) VALUES (14,'Magallanes y Antártica Chilena');
INSERT INTO toshivepet.core_region (codigoRegion, nombreRegion) VALUES (15,'Metropolitana de Santiago');

INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (0,'Arica',0);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (1,'Camarones',0);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (2,'Putre',0);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (3,'General Lagos',0);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (4,'Iquique',1);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (5,'Alto Hospicio',1);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (6,'Pozo Almonte',1);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (7,'Camiña',1);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (8,'Colchane',1);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (9,'Huara',1);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (10,'Pica',1);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (11,'Antofagasta',2);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (12,'Mejillones',2);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (13,'Sierra Gorda',2);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (14,'Taltal',2);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (15,'Calama',2);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (16,'Ollagüe',2);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (17,'San Pedro de Atacama',2);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (18,'Tocopilla',2);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (19,'María Elena',2);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (20,'Copiapó',3);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (21,'Caldera',3);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (22,'Tierra Amarilla',3);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (23,'Chañaral',3);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (24,'Diego de Almagro',3);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (25,'Vallenar',3);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (26,'Alto del Carmen',3);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (27,'Freirina',3);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (28,'Huasco',3);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (29,'La Serena',4);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (30,'Coquimbo',4);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (31,'Andacollo',4);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (32,'La Higuera',4);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (33,'Paihuano',4);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (34,'Vicuña',4);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (35,'Illapel',4);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (36,'Canela',4);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (37,'Los Vilos',4);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (38,'Salamanca',4);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (39,'Ovalle',4);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (40,'Combarbalá',4);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (41,'Monte Patria',4);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (42,'Punitaqui',4);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (43,'Río Hurtado',4);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (44,'Valparaíso',5);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (45,'Casablanca',5);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (46,'Concón',5);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (47,'Juan Fernández',5);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (48,'Puchuncaví',5);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (49,'Quintero',5);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (50,'Viña del Mar',5);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (51,'Isla de Pascua',5);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (52,'Los Andes',5);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (53,'Calle Larga',5);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (54,'Rinconada',5);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (55,'San Esteban',5);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (56,'La Ligua',5);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (57,'Cabildo',5);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (58,'Papudo',5);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (59,'Petorca',5);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (60,'Zapallar',5);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (61,'Quillota',5);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (62,'La Calera',5);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (63,'Hijuelas',5);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (64,'La Cruz',5);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (65,'Nogales',5);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (66,'San Antonio',5);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (67,'Algarrobo',5);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (68,'Cartagena',5);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (69,'El Quisco',5);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (70,'El Tabo',5);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (71,'Santo Domingo',5);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (72,'San Felipe',5);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (73,'Catemu',5);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (74,'Llay-Llay',5);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (75,'Panquehue',5);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (76,'Putaendo',5);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (77,'Santa María',5);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (78,'Quilpué',5);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (79,'Limache',5);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (80,'Olmué',5);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (81,'Villa Alemana',5);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (82,'Rancagua',6);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (83,'Codegua',6);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (84,'Coinco',6);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (85,'Coltauco',6);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (86,'Doñihue',6);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (87,'Graneros',6);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (88,'Las Cabras',6);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (89,'Machalí',6);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (90,'Malloa',6);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (91,'Mostazal',6);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (92,'Olivar',6);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (93,'Peumo',6);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (94,'Pichidegua',6);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (95,'Quinta de Tilcoco',6);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (96,'Rengo',6);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (97,'Requínoa',6);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (98,'San Vicente',6);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (99,'Pichilemu',6);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (100,'La Estrella',6);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (101,'Litueche',6);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (102,'Marchigüe',6);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (103,'Navidad',6);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (104,'Paredones',6);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (105,'San Fernando',6);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (106,'Chépica',6);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (107,'Chimbarongo',6);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (108,'Lolol',6);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (109,'Nancagua',6);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (110,'Palmilla',6);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (111,'Peralillo',6);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (112,'Placilla',6);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (113,'Pumanque',6);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (114,'Santa Cruz',6);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (115,'Talca',7);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (116,'Constitución',7);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (117,'Curepto',7);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (118,'Empedrado',7);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (119,'Maule',7);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (120,'Pelarco',7);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (121,'Pencahue',7);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (122,'Río Claro',7);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (123,'San Clemente',7);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (124,'San Rafael',7);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (125,'Cauquenes',7);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (126,'Chanco',7);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (127,'Pelluhue',7);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (128,'Curicó',7);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (129,'Hualañé',7);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (130,'Licantén',7);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (131,'Molina',7);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (132,'Rauco',7);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (133,'Romeral',7);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (134,'Sagrada Familia',7);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (135,'Teno',7);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (136,'Vichuquén',7);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (137,'Linares',7);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (138,'Colbún',7);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (139,'Longaví',7);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (140,'Parral',7);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (141,'Retiro',7);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (142,'San Javier',7);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (143,'Villa Alegre',7);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (144,'Yerbas Buenas',7);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (145,'Chillán',8);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (146,'Bulnes',8);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (147,'Chillán Viejo',8);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (148,'El Carmen',8);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (149,'Pemuco',8);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (150,'Pinto',8);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (151,'Quillón',8);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (152,'San Ignacio',8);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (153,'Yungay',8);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (154,'Quirihue',8);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (155,'Cobquecura',8);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (156,'Coelemu',8);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (157,'Ninhue',8);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (158,'Portezuelo',8);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (159,'Ránquil',8);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (160,'Treguaco',8);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (161,'San Carlos',8);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (162,'Coihueco',8);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (163,'Ñiquén',8);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (164,'San Fabián',8);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (165,'San Nicolás',8);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (166,'Concepción',9);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (167,'Coronel',9);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (168,'Chiguayante',9);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (169,'Florida',9);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (170,'Hualqui',9);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (171,'Lota',9);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (172,'Penco',9);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (173,'San Pedro de La Paz',9);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (174,'Santa Juana',9);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (175,'Talcahuano',9);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (176,'Tomé',9);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (177,'Hualpén',9);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (178,'Lebu',9);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (179,'Arauco',9);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (180,'Cañete',9);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (181,'Contulmo',9);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (182,'Curanilahue',9);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (183,'Los Álamos',9);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (184,'Tirúa',9);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (185,'Los Ángeles',9);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (186,'Antuco',9);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (187,'Cabrero',9);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (188,'Laja',9);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (189,'Mulchén',9);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (190,'Nacimiento',9);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (191,'Negrete',9);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (192,'Quilaco',9);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (193,'Quilleco',9);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (194,'San Rosendo',9);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (195,'Santa Bárbara',9);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (196,'Tucapel',9);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (197,'Yumbel',9);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (198,'Alto Biobío',9);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (199,'Temuco',10);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (200,'Carahue',10);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (201,'Cunco',10);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (202,'Curarrehue',10);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (203,'Freire',10);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (204,'Galvarino',10);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (205,'Gorbea',10);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (206,'Lautaro',10);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (207,'Loncoche',10);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (208,'Melipeuco',10);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (209,'Nueva Imperial',10);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (210,'Padre Las Casas',10);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (211,'Perquenco',10);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (212,'Pitrufquén',10);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (213,'Pucón',10);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (214,'Saavedra',10);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (215,'Teodoro Schmidt',10);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (216,'Toltén',10);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (217,'Vilcún',10);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (218,'Villarrica',10);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (219,'Cholchol',10);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (220,'Angol',10);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (221,'Collipulli',10);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (222,'Curacautín',10);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (223,'Ercilla',10);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (224,'Lonquimay',10);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (225,'Los Sauces',10);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (226,'Lumaco',10);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (227,'Purén',10);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (228,'Renaico',10);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (229,'Traiguén',10);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (230,'Victoria',10);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (231,'Valdivia',11);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (232,'Corral',11);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (233,'Lanco',11);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (234,'Los Lagos',11);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (235,'Máfil',11);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (236,'Mariquina',11);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (237,'Paillaco',11);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (238,'Panguipulli',11);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (239,'La Unión',11);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (240,'Futrono',11);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (241,'Lago Ranco',11);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (242,'Río Bueno',11);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (243,'Puerto Montt',12);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (244,'Calbuco',12);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (245,'Cochamó',12);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (246,'Fresia',12);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (247,'Frutillar',12);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (248,'Los Muermos',12);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (249,'Llanquihue',12);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (250,'Maullín',12);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (251,'Puerto Varas',12);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (252,'Castro',12);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (253,'Ancud',12);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (254,'Chonchi',12);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (255,'Curaco de Vélez',12);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (256,'Dalcahue',12);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (257,'Puqueldón',12);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (258,'Queilén',12);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (259,'Quellón',12);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (260,'Quemchi',12);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (261,'Quinchao',12);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (262,'Osorno',12);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (263,'Puerto Octay',12);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (264,'Purranque',12);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (265,'Puyehue',12);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (266,'Río Negro',12);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (267,'San Juan de la Costa',12);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (268,'San Pablo',12);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (269,'Chaitén',12);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (270,'Futaleufú',12);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (271,'Hualaihué',12);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (272,'Palena',12);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (273,'Coyhaique',13);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (274,'Lago Verde',13);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (275,'Aysén',13);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (276,'Cisnes',13);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (277,'Guaitecas',13);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (278,'Cochrane',13);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (279,q'[OHiggins]',13);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (280,'Tortel',13);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (281,'Chile Chico',13);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (282,'Río Ibáñez',13);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (283,'Punta Arenas',14);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (284,'Laguna Blanca',14);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (285,'Río Verde',14);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (286,'San Gregorio',14);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (287,'Cabo de Hornos',14);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (288,'Antártica',14);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (289,'Porvenir',14);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (290,'Primavera',14);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (291,'Timaukel',14);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (292,'Natales',14);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (293,'Torres del Paine',14);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (294,'Santiago',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (295,'Cerrillos',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (296,'Cerro Navia',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (297,'Conchalí',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (298,'El Bosque',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (299,'Estación Central',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (300,'Huechuraba',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (301,'Independencia',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (302,'La Cisterna',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (303,'La Florida',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (304,'La Granja',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (305,'La Pintana',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (306,'La Reina',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (307,'Las Condes',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (308,'Lo Barnechea',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (309,'Lo Espejo',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (310,'Lo Prado',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (311,'Macul',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (312,'Maipú',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (313,'Ñuñoa',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (314,'Pedro Aguirre Cerda',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (315,'Peñalolén',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (316,'Providencia',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (317,'Pudahuel',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (318,'Quilicura',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (319,'Quinta Normal',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (320,'Recoleta',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (321,'Renca',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (322,'San Joaquín',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (323,'San Miguel',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (324,'San Ramón',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (325,'Vitacura',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (326,'Puente Alto',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (327,'Pirque',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (328,'San José de Maipo',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (329,'Colina',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (330,'Lampa',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (331,'Til Til',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (332,'San Bernardo',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (333,'Buin',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (334,'Calera de Tango',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (335,'Paine',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (336,'Melipilla',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (337,'Alhué',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (338,'Curacaví',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (339,'María Pinto',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (340,'San Pedro',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (341,'Talagante',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (342,'El Monte',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (343,'Isla de Maipo',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (344,'Padre Hurtado',15);
INSERT INTO toshivepet.core_comuna (codigoComuna, nombreComuna, region_id) VALUES (345,'Peñaflor',15);