# Generated by Django 3.0.7 on 2023-07-09 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('codigoComuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombreComuna', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('idDireccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCalle', models.CharField(max_length=30)),
                ('codigoPostal', models.CharField(max_length=40)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('idPregunta', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Pregunta')),
                ('pregunta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('codigoRegion', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo de Region')),
                ('nombreRegion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False)),
                ('nombreRol', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('idTipo', models.AutoField(primary_key=True, serialize=False, verbose_name='Id tipo')),
                ('descripcion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombreUsuario', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=20)),
                ('clave', models.CharField(max_length=20)),
                ('respuesta', models.CharField(max_length=20)),
                ('idPregunta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Pregunta')),
                ('idRol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Rol')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=300)),
                ('descripcionProducto', models.CharField(max_length=500)),
                ('stock', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('foto', models.ImageField(upload_to='toshibedjango')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idPedido', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Pedido')),
                ('fechaPedido', models.DateTimeField(verbose_name='Fecha de Pedido')),
                ('fechaEntrega', models.DateTimeField(verbose_name='Fecha de Entrega')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('idDireccion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Direccion', verbose_name='ID de Dirección')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='direccion',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Usuario'),
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('idDetalle', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Detalle')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Pedido', verbose_name='ID de Pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Producto', verbose_name='ID de Producto')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Region'),
        ),
    ]
